apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-28T04:25:53Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3216"
  uid: 70897363-20ce-4c91-bbc9-33c1481294c7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.106.216
  clusterIPs:
  - 10.101.106.216
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30791
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
